version: '2'
services:
#Service odoo13 toma el Dockerfile de ./build/odoo13
 odoo13:
  build: ./build/odoo13
  #Mapea el 8069 del container al anfitrión
  ports:
  - "8069:8069"
  #Cambiarlo para el home de cada usuario
  volumes:
  - /home/javierfp/odoo13:/opt/odoo/src
